### PR TITLE
Implemented a better dangerScore function

### PR DESCRIPTION
**Pull request by raadkhan**
- Calculated danger score by taking sum of obstacle's average angle score and obstacle's closest distance score (relative to the robot)
- Wrote two supplementary functions: getMinDistance( ) and getMaxDistance( )
- Wrote a gtest for dangerScore( ) and  passed

### CODE REVIEW

**Comment by raadkhan** [comment]
Forgot to push LidarDecision.h which contained the new function definitions, and need to resolve merge conflicts

**Comment by raadkhan** [comment]
Pushed LidarDecision.h with new function definitions

**Comment by garethellis0** [comment]
Everything looks good, but git appears to have sh** the bed, and thinks you deleted and re-added massive chunks of the file. Before I merge, can I confirm that all you've done is added `getMinDistance()` and `getMaxDistance()`, updated the `dangerScore()` function, and added a test for it?

Also, you can put stuff in code boxes in git comments like this: \` some code \`, or if you want to put it in a block, like this:
\```
Here is some code
\```

(I've escaped the \` characters above so you can see them. Normally this would look like this: `some code` and this:
```
Here is some code
```

**Comment by raadkhan** [comment]
I can confirm I have not deleted any files.
```
Here is some more code
```

**Comment by garethellis0** [comment]
Yeah, I was more referring to the changes you made, namely:
- added getMinDistance() and getMaxDistance()
- updated the dangerScore() function, and added a test for it

**Comment by raadkhan** [comment]
Ah right and made the minor fixes, yes

**Pull request merged**
