### PR TITLE
Added support for Razor IMU

### PR DESCRIPTION
**Pull request by raadkhan**
- Added python-visual and python-wxtools as dependencies
- Added https://github.com/KristofRobot/razor_imu_9dof as a submodule

### CODE REVIEW

**Comment by garethellis0** [comment]
Stuff is failing? Note to self: might need to add folder?

**Comment by garethellis0** [comment]
@raadkhan, did you have any config files that you changed to get this to run properly (other then specifying the usb port)

**Comment by raadkhan** [comment]
@garethellis0, I only recall changing my_razor.yaml

**Comment by garethellis0** [comment]
@raadkhan was that just to set the USB port?

**Comment by raadkhan** [comment]
@garethellis0 that was it. Are you encountering any problems?

**Comment by garethellis0** [comment]
Nope, just want to confirm that we didn't need to set any calibration settings or anything like that. All looks good. :+1:

**Pull request merged**
