### PR TITLE
Vision param save

### LINKED ISSUE #28: Saving color calibration to a file or the param server

### PR DESCRIPTION
**Pull request by ValRat**
Fixes #28

### CODE REVIEW

**Comment by garethellis0** [comment]
Also I've created #29 for after #28 is resolved.

**Comment by ValRat** [comment]
@garethellis0 , do you mean #35 ?

**Comment by garethellis0** [comment]
Yup, sorry @ValRat , edited my comment accordingly

**Comment by garethellis0** [comment]
For future reference, this pull request was referring to **Saving Vision Params to File**

**Pull request merged**
